name: Deploy github page

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-04-28
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.4.0
      - uses: jetli/wasm-bindgen-action@v0.2.0

      - uses: actions/checkout@v2

      - run: trunk build --release

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        if: github.event_name != 'pull_request'
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./dist # The folder the action should deploy.
